version: '3.3'

services:

  chatbotapi2:
    image: registry.dpvsoft.com/chatbotapi2:480
    container_name: chatbotapi2
    restart: always
    labels:
      - "traefik.docker.network=web"
      - "traefik.enabled=true"
      - "traefik.backend=chatbotapi2"
      - "traefik.frontend.rule=Host:chatbotapi2.dpvsoft.com"
      - "traefik.port=80"
    networks:
      - web
   
networks:
  web:
    external: true
